---
contests:
  - contest_name: School Board
    contest_type: candidate
    open_positions: 1
    tally: rcv
    choices:
    - name: Ann A
      party: Circle Party
    - name: Bob B
      party: Dyad Party
    - name: Cindy C
      party: Triangle Party
    - name: Derek D
      party: Square Party
  - contest_name: Select Board
    contest_type: candidate
    open_positions: 3
    tally: rcv
    choices:
    - name: Anthony Alpha
      party: Circle Party
    - name: Betty Beta
      party: Dyad Party
    - name: Gloria Gamma
      party: Triangle Party
    - name: David Delta
      party: Square Party
    - name: Emily Echo
      party: Pentagon Party
    - name: Francis Foxtrot
      party: Hexagon Party
voting centers:
- Concord Carlisle High School:
    street: 500 Walden St, Concord, MA 01742
    id: 000001
submodules: []
